var http = require("http");
var server = http.createServer(function(request, response) {
  response.writeHead(200, {"Content-Type": "text/html"});
  response.write("<!DOCTYPE \"html\">");
  response.write("<html>");
  response.write("<head>");
  response.write("<title>NiftyNico.me</title>");
  response.write("</head>");
  response.write("<body bgcolor=\"#000000\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");
  response.write("<img src=\"http://stream1.gifsoup.com/view4/1982008/sefus-urkel-dance-o.gif\">");

  response.write("<iframe width=\"0\" height=\"0\" src=\"http://www.youtube.com/embed/-tlhMRoNJrs?autoplay=1&loop=1&cc_load_policy=1\" frameborder=\"0\" allowfullscreen></iframe>");
  response.write("</body>");
  response.write("</html>");
  response.end();
});
 
server.listen(80);
console.log("Server is listening");
